# Generated by Django 2.1.1 on 2020-05-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('winery', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('wine_type', models.CharField(max_length=30)),
            ],
        ),
    ]
