# Generated by Django 2.1.1 on 2020-05-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addwine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wine',
            new_name='bottle',
        ),
    ]
